// AUTO-GENERATED by @caffeinejs/cli — do not edit or commit
// Regenerate: caffeine generate modules

import { mod, type Module } from '@caffeinejs/di'

import { CatsController } from './cats.controller.js'
import { CatsService } from './cats.service.js'

export const catsModule: Module = mod({
  name: 'cats',
  provides: () => [CatsController, CatsService],
})
