export type { Backend, LockLease } from './backend.js'
export type { DistLockBuilder } from './builder.js'
export { CaffeineDistLock } from './distlock.js'
export { distLockConfigSchema, type DistLockConfigSlice } from './config.js'
export type { AcquireOptions, DistLock, Lock, OnceOptions, OnceResult } from './distlock.js'
export { ErrDistLock, ErrDistLockConfiguration, ErrLockNotAcquired } from './errors.js'
export { kDistLock, kDistLockBackend } from './keys.js'
export { DEFAULT_DIST_LOCK_OPTIONS, type DistLockOptions } from './options.js'
export { distlock, type DistLockConfigure } from './plugin.js'
