export const kCORS = Symbol('@caffeinejs/http::fastify.route.cors')
export const kConfig = Symbol('@caffeinejs/http::fastify.route.config')
export const kRouteOptions = Symbol('@caffeinejs/http::fastify.route.options')
export const kBodyBuffer = Symbol('@caffeinejs/http::fastify.route.body_buffer')
export const kBodyStream = Symbol('@caffeinejs/http::fastify.route.body_stream')
export const kCompress = Symbol('@caffeinejs/http::fastify.route.compress')
