export const kCORS = Symbol('caffeine.http.route.cors')
export const kConfig = Symbol('caffeine.http.route.config')
export const kRouteOptions = Symbol('caffeine.http.route.options')
export const kBodyBuffer = Symbol('caffeine.http.route.body_buffer')
export const kBodyStream = Symbol('caffeine.http.route.body_stream')
export const kCompress = Symbol('caffeine.http.route.compress')
