// AUTO-GENERATED by @caffeinejs/cli — do not edit
// Regenerate: caffeine generate modules

import { mod, type Module } from '@caffeinejs/di'
import { utilModule } from '../util/util.gen.mod.js'
import { PetsController } from './pets.controller.js'
import { PetsRepository } from './pets.repository.js'

export const petsModule: Module = mod({
  name: 'pets',
  needs: () => [
    utilModule,
  ],
  provides: () => [
    PetsController,
    PetsRepository,
  ],
})
