import { dirname, relative, resolve } from 'node:path'

const HEADER = [
  '// AUTO-GENERATED by @caffeinejs/cli — do not edit or commit',
  '// Regenerate: caffeine generate',
].join('\n')

export interface NamedImport {
  exportName: string
  alias: string
  importPath: string
}

export interface FolderModuleSource {
  exportName: string
  moduleName: string
  sideEffectImports: string[]
  needs: NamedImport[]
}

export interface RootModuleSource {
  modules: NamedImport[]
}

export function renderFolderModule(source: FolderModuleSource): string {
  const needs = sortNamedImports(source.needs)
  const lines = [
    HEADER,
    '',
    "import { mod, type Module } from '@caffeinejs/di'",
    ...relativeImportLines(source.sideEffectImports, needs),
    '',
    renderModConst(source.exportName, source.moduleName, needs),
    '',
  ]
  return lines.join('\n')
}

export function renderRootModule(source: RootModuleSource): string {
  const modules = sortNamedImports(source.modules)
  const lines = [
    HEADER,
    '',
    "import { mod, type Module } from '@caffeinejs/di'",
    ...modules.map(renderNamedImport),
    '',
    'export const rootModule: Module = mod({',
    "  name: 'root',",
    `  provides: () => ${renderThunkArray(
      modules.map(m => m.alias),
      '  ',
    )},`,
    '})',
    '',
  ]
  return lines.join('\n')
}

export async function writeIfChanged(path: string, content: string): Promise<boolean> {
  const outputFile = Bun.file(path)
  let existing: string | undefined
  if (await outputFile.exists()) {
    existing = await outputFile.text()
  }
  if (existing !== undefined && hash(existing) === hash(content)) {
    return false
  }
  await Bun.write(path, content)
  return true
}

export function toImportPath(fromDir: string, absTarget: string, importExtension: '.js' | '.ts' | ''): string {
  let rel = relative(fromDir, absTarget).replaceAll('\\', '/')
  if (!rel.startsWith('.')) {
    rel = './' + rel
  }
  return rel.replace(/\.tsx?$/u, importExtension)
}

export function resolveSpecifier(fromFile: string, spec: string): string {
  const abs = resolve(dirname(fromFile), spec)
  if (abs.endsWith('.js')) {
    return abs.slice(0, -3) + '.ts'
  }
  if (abs.endsWith('.mjs') || abs.endsWith('.cjs')) {
    return abs.slice(0, -4) + '.ts'
  }
  if (!/\.[A-Za-z0-9]+$/u.test(abs)) {
    return abs + '.ts'
  }
  return abs
}

function renderNamedImport(item: NamedImport): string {
  if (item.alias === item.exportName) {
    return `import { ${item.exportName} } from '${item.importPath}'`
  }
  return `import { ${item.exportName} as ${item.alias} } from '${item.importPath}'`
}

function renderModConst(exportName: string, moduleName: string, needs: NamedImport[]): string {
  if (needs.length === 0) {
    return `export const ${exportName}: Module = mod({ name: '${escapeQuotes(moduleName)}' })`
  }
  return [
    `export const ${exportName}: Module = mod({`,
    `  name: '${escapeQuotes(moduleName)}',`,
    `  needs: () => ${renderThunkArray(
      needs.map(n => n.alias),
      '  ',
    )},`,
    `})`,
  ].join('\n')
}

function renderThunkArray(aliases: string[], indent: string): string {
  const inner = indent + '  '
  const body = aliases.map(alias => `${inner}${alias},`).join('\n')
  return `[\n${body}\n${indent}]`
}

function sortNamedImports(items: NamedImport[]): NamedImport[] {
  return [...items].sort((a, b) => {
    const byPath = a.importPath.localeCompare(b.importPath)
    if (byPath !== 0) {
      return byPath
    }
    return a.exportName.localeCompare(b.exportName)
  })
}

function relativeImportLines(sideEffectImports: string[], named: NamedImport[]): string[] {
  const rows: Array<{ path: string; line: string }> = [
    ...sideEffectImports.map(p => ({ path: p, line: `import '${p}'` })),
    ...named.map(item => ({ path: item.importPath, line: renderNamedImport(item) })),
  ]
  rows.sort((a, b) => {
    const byPath = a.path.localeCompare(b.path)
    if (byPath !== 0) {
      return byPath
    }
    return a.line.localeCompare(b.line)
  })
  return rows.map(row => row.line)
}

function escapeQuotes(value: string): string {
  return value.replaceAll('\\', '\\\\').replaceAll("'", "\\'")
}

function hash(content: string): string {
  return new Bun.CryptoHasher('sha1').update(content).digest('hex')
}
