import { afterEach, describe, expect, it } from 'bun:test'
import { randomUUID } from 'node:crypto'
import { rm } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join } from 'node:path'

import { generate } from './generator.js'

function tempDir(): string {
  return join(tmpdir(), `caffeine-test-${randomUUID()}`)
}

describe('generate()', () => {
  const dirs: string[] = []

  afterEach(async () => {
    for (const d of dirs.splice(0)) {
      await rm(d, { recursive: true, force: true })
    }
  })

  it('writes side-effect imports sorted alphabetically', async () => {
    const dir = tempDir()
    dirs.push(dir)
    await Bun.write(join(dir, 'a.ts'), '')
    await Bun.write(join(dir, 'b.ts'), '')
    await Bun.write(join(dir, 'c.ts'), '')

    const output = join(dir, '__imports__.gen.ts')
    const files = [join(dir, 'b.ts'), join(dir, 'a.ts'), join(dir, 'c.ts')]

    const changed = await generate({ files, output, importExtension: '.js' })

    expect(changed).toBe(true)
    const content = await Bun.file(output).text()
    expect(content).toContain("import './a.js'")
    expect(content).toContain("import './b.js'")
    expect(content).toContain("import './c.js'")
    const aIdx = content.indexOf("import './a.js'")
    const bIdx = content.indexOf("import './b.js'")
    const cIdx = content.indexOf("import './c.js'")
    expect(aIdx).toBeLessThan(bIdx)
    expect(bIdx).toBeLessThan(cIdx)
  })

  it('replaces .ts with configured importExtension', async () => {
    const dir = tempDir()
    dirs.push(dir)
    await Bun.write(join(dir, 'foo.ts'), '')

    const output = join(dir, '__imports__.gen.ts')
    await generate({ files: [join(dir, 'foo.ts')], output, importExtension: '.ts' })

    const content = await Bun.file(output).text()
    expect(content).toContain("import './foo.ts'")
  })

  it('strips extension when importExtension is empty string', async () => {
    const dir = tempDir()
    dirs.push(dir)
    await Bun.write(join(dir, 'foo.ts'), '')

    const output = join(dir, '__imports__.gen.ts')
    await generate({ files: [join(dir, 'foo.ts')], output, importExtension: '' })

    const content = await Bun.file(output).text()
    expect(content).toContain("import './foo'")
  })

  it('includes auto-generated header', async () => {
    const dir = tempDir()
    dirs.push(dir)

    const output = join(dir, '__imports__.gen.ts')
    await generate({ files: [], output, importExtension: '.js' })

    const content = await Bun.file(output).text()
    expect(content).toContain('// AUTO-GENERATED by @caffeinejs/cli')
    expect(content).toContain('// Regenerate: caffeine generate')
  })

  it('returns false and skips write when content unchanged', async () => {
    const dir = tempDir()
    dirs.push(dir)
    await Bun.write(join(dir, 'a.ts'), '')

    const output = join(dir, '__imports__.gen.ts')
    const files = [join(dir, 'a.ts')]
    await generate({ files, output, importExtension: '.js' })
    const stat1 = Bun.file(output).lastModified

    await Bun.sleep(5)
    const changed = await generate({ files, output, importExtension: '.js' })

    expect(changed).toBe(false)
    expect(Bun.file(output).lastModified).toBe(stat1)
  })

  it('returns true on first write', async () => {
    const dir = tempDir()
    dirs.push(dir)

    const output = join(dir, '__imports__.gen.ts')
    const changed = await generate({ files: [], output, importExtension: '.js' })
    expect(changed).toBe(true)
  })
})
