import { afterEach, describe, expect, it } from 'bun:test'
import { randomUUID } from 'node:crypto'
import { rm } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join } from 'node:path'

import { generateModules } from './modules_generator.js'

function tempDir(): string {
  return join(tmpdir(), `caffeine-test-${randomUUID()}`)
}

describe('generateModules()', () => {
  const dirs: string[] = []

  afterEach(async () => {
    for (const d of dirs.splice(0)) {
      await rm(d, { recursive: true, force: true })
    }
  })

  it('generates namespace imports for each file', async () => {
    const dir = tempDir()
    dirs.push(dir)
    await Bun.write(join(dir, 'order', 'order.mod.ts'), '')
    await Bun.write(join(dir, 'users', 'users.mod.ts'), '')

    const output = join(dir, 'app.mod.ts')
    const files = [join(dir, 'order', 'order.mod.ts'), join(dir, 'users', 'users.mod.ts')]
    await generateModules({ files, output, importExtension: '.js' })

    const content = await Bun.file(output).text()
    expect(content).toContain("import * as _0 from './order/order.mod.js'")
    expect(content).toContain("import * as _1 from './users/users.mod.js'")
  })

  it('exports modules array with _pick calls for each file', async () => {
    const dir = tempDir()
    dirs.push(dir)
    await Bun.write(join(dir, 'a.mod.ts'), '')
    await Bun.write(join(dir, 'b.mod.ts'), '')

    const output = join(dir, 'app.mod.ts')
    const files = [join(dir, 'a.mod.ts'), join(dir, 'b.mod.ts')]
    await generateModules({ files, output, importExtension: '.js' })

    const content = await Bun.file(output).text()
    expect(content).toContain('export const modules: Array<Module | ModuleFn> = [')
    expect(content).toContain('..._pick(_0),')
    expect(content).toContain('..._pick(_1),')
  })

  it('includes _pick function that handles default and named exports', async () => {
    const dir = tempDir()
    dirs.push(dir)

    const output = join(dir, 'app.mod.ts')
    await generateModules({ files: [], output, importExtension: '.js' })

    const content = await Bun.file(output).text()
    expect(content).toContain('function _pick(')
    expect(content).toContain("ns['default']")
    expect(content).toContain('[kModule]')
  })

  it('imports kModule and Module from @caffeinejs/di', async () => {
    const dir = tempDir()
    dirs.push(dir)

    const output = join(dir, 'app.mod.ts')
    await generateModules({ files: [], output, importExtension: '.js' })

    const content = await Bun.file(output).text()
    expect(content).toContain("import { kModule } from '@caffeinejs/di'")
    expect(content).toContain("import type { Module, ModuleFn } from '@caffeinejs/di'")
  })

  it('includes auto-generated header', async () => {
    const dir = tempDir()
    dirs.push(dir)

    const output = join(dir, 'app.mod.ts')
    await generateModules({ files: [], output, importExtension: '.js' })

    const content = await Bun.file(output).text()
    expect(content).toContain('// AUTO-GENERATED by @caffeinejs/cli')
    expect(content).toContain('// Regenerate: caffeine generate')
  })

  it('returns false and skips write when content unchanged', async () => {
    const dir = tempDir()
    dirs.push(dir)
    await Bun.write(join(dir, 'a.mod.ts'), '')

    const output = join(dir, 'app.mod.ts')
    const files = [join(dir, 'a.mod.ts')]
    await generateModules({ files, output, importExtension: '.js' })
    const stat1 = Bun.file(output).lastModified

    await Bun.sleep(5)
    const changed = await generateModules({ files, output, importExtension: '.js' })

    expect(changed).toBe(false)
    expect(Bun.file(output).lastModified).toBe(stat1)
  })

  it('returns true on first write', async () => {
    const dir = tempDir()
    dirs.push(dir)

    const output = join(dir, 'app.mod.ts')
    const changed = await generateModules({ files: [], output, importExtension: '.js' })
    expect(changed).toBe(true)
  })

  it('replaces .ts with configured importExtension', async () => {
    const dir = tempDir()
    dirs.push(dir)
    await Bun.write(join(dir, 'a.mod.ts'), '')

    const output = join(dir, 'app.mod.ts')
    await generateModules({ files: [join(dir, 'a.mod.ts')], output, importExtension: '.ts' })

    const content = await Bun.file(output).text()
    expect(content).toContain("import * as _0 from './a.mod.ts'")
  })
})
