import { randomUUID } from 'node:crypto'
import { mkdir, rm } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { afterEach, describe, expect, it } from 'bun:test'
import { generateModuleGraph } from './module_graph_generator.js'

function tempDir(): string {
  return join(tmpdir(), `caffeine-test-${randomUUID()}`)
}

describe('generateModuleGraph()', () => {
  const dirs: string[] = []

  afterEach(async () => {
    for (const d of dirs.splice(0)) {
      await rm(d, { recursive: true, force: true })
    }
  })

  async function writeTree(root: string, files: Record<string, string>): Promise<void> {
    for (const [rel, text] of Object.entries(files)) {
      const abs = join(root, rel)
      await mkdir(join(abs, '..'), { recursive: true })
      await Bun.write(abs, text)
    }
  }

  it('emits per-folder generated modules, app, and a provides-only root', async () => {
    const dir = tempDir()
    dirs.push(dir)

    await writeTree(dir, {
      'src/app.ts': '@Injectable()\nexport class App {}\n',
      'src/app.di.ts': '@Injectable()\nexport class AppDi {}\n',
      'src/orders/order.service.ts': 'import { User } from \'../users/user.service.js\'\n@Injectable()\nexport class OrderService { constructor(private user: User) {} }\n',
      'src/users/user.service.ts': '@Injectable()\nexport class User {}\n',
      'src/libs/db/client.ts': '@Injectable()\nexport class Db {}\n',
      'src/libs/cache/cache.ts': '@Injectable()\nexport class Cache {}\n',
      'src/libs/util.ts': '@Injectable()\nexport class Util {}\n',
      'src/vendor/skip.ts': '@Injectable()\nexport class Skip {}\n',
      'src/orders/orders.mod.ts': 'export const extraOrdersModule = { name: \'extra\' }\n',
    })

    const result = await generateModuleGraph({
      cwd: dir,
      config: {
        include: ['src/**/*.ts'],
        exclude: ['**/app.di.ts'],
        root: 'src',
        depths: { libs: 2 },
        skip: ['vendor'],
        maxDepth: 8,
      },
    })

    expect(result.changed).toBe(true)
    expect(result.modules).toBe(5)

    const orders = await Bun.file(join(dir, 'src/orders/orders.generated.mod.ts')).text()
    const users = await Bun.file(join(dir, 'src/users/users.generated.mod.ts')).text()
    const db = await Bun.file(join(dir, 'src/libs/db/db.generated.mod.ts')).text()
    const cache = await Bun.file(join(dir, 'src/libs/cache/cache.generated.mod.ts')).text()
    const app = await Bun.file(join(dir, 'src/app.generated.mod.ts')).text()
    const root = await Bun.file(join(dir, 'src/root.generated.mod.ts')).text()

    expect(await Bun.file(join(dir, 'src/libs/libs.generated.mod.ts')).exists()).toBe(false)
    expect(await Bun.file(join(dir, 'src/orders/orders.mod.ts')).text()).toContain('extraOrdersModule')

    expect(orders).toContain('import \'./order.service.js\'')
    expect(orders).not.toContain('OrderService')
    expect(orders).toContain('import { usersModule } from \'../users/users.generated.mod.js\'')
    expect(orders).toContain('import { extraOrdersModule } from \'./orders.mod.js\'')
    expect(orders.indexOf('\'../users/users.generated.mod.js\'')).toBeLessThan(
      orders.indexOf('\'./order.service.js\''),
    )
    expect(orders.indexOf('\'./order.service.js\'')).toBeLessThan(
      orders.indexOf('\'./orders.mod.js\''),
    )
    expect(orders).toContain([
      '  needs: () => [',
      '    usersModule,',
      '    extraOrdersModule,',
      '  ],',
    ].join('\n'))
    expect(orders).toContain('name: \'orders\'')

    expect(users).toContain('export const usersModule: Module = mod({ name: \'users\' })')
    expect(users).toContain('import \'./user.service.js\'')

    expect(db).toContain('mod({ name: \'db\' })')
    expect(cache).toContain('mod({ name: \'cache\' })')

    expect(app).toContain('import \'./app.js\'')
    expect(app).toContain('import \'./libs/util.js\'')
    expect(app).not.toContain('app.di')
    expect(app).toContain('mod({ name: \'app\' })')

    expect(root).toContain('name: \'root\'')
    expect(root).toContain([
      '  provides: () => [',
      '    appModule,',
      '    cacheModule,',
      '    dbModule,',
      '    ordersModule,',
      '    usersModule,',
      '  ],',
    ].join('\n'))
    expect(root).not.toContain('needs:')
    expect(root).toContain('appModule')
    expect(root).toContain('ordersModule')
    expect(root).toContain('usersModule')
    expect(root).toContain('dbModule')
    expect(root).toContain('cacheModule')
    expect(root).not.toContain('Skip')
    expect(root).toContain('// AUTO-GENERATED by @caffeinejs/cli')
  })

  it('does not overwrite handwritten *.mod.ts', async () => {
    const dir = tempDir()
    dirs.push(dir)
    const handwritten = 'export const ordersModule = { name: \'hand\' }\n'
    await writeTree(dir, {
      'src/orders/order.service.ts': '@Injectable()\nexport class OrderService {}\n',
      'src/orders/orders.mod.ts': handwritten,
    })

    await generateModuleGraph({
      cwd: dir,
      config: { include: ['src/**/*.ts'], root: 'src' },
    })

    expect(await Bun.file(join(dir, 'src/orders/orders.mod.ts')).text()).toBe(handwritten)
    expect(await Bun.file(join(dir, 'src/orders/orders.generated.mod.ts')).exists()).toBe(true)
  })

  it('drops files deeper than maxDepth', async () => {
    const dir = tempDir()
    dirs.push(dir)
    await writeTree(dir, {
      'src/orders/order.ts': '@Injectable()\nexport class Order {}\n',
      'src/a/b/c/d/deep.ts': '@Injectable()\nexport class Deep {}\n',
    })

    await generateModuleGraph({
      cwd: dir,
      config: { include: ['src/**/*.ts'], root: 'src', maxDepth: 1 },
    })

    expect(await Bun.file(join(dir, 'src/orders/orders.generated.mod.ts')).exists()).toBe(true)
    expect(await Bun.file(join(dir, 'src/a/a.generated.mod.ts')).exists()).toBe(false)
    const root = await Bun.file(join(dir, 'src/root.generated.mod.ts')).text()
    expect(root).not.toContain('deep')
  })

  it('applies moduleName to the name field only', async () => {
    const dir = tempDir()
    dirs.push(dir)
    await writeTree(dir, {
      'src/orders/order.ts': '@Injectable()\nexport class Order {}\n',
    })

    await generateModuleGraph({
      cwd: dir,
      config: {
        include: ['src/**/*.ts'],
        root: 'src',
        moduleName: name => name.toUpperCase(),
      },
    })

    const orders = await Bun.file(join(dir, 'src/orders/orders.generated.mod.ts')).text()
    expect(orders).toContain('name: \'ORDERS\'')
    expect(orders).toContain('export const ordersModule')
  })

  it('returns false when content is unchanged', async () => {
    const dir = tempDir()
    dirs.push(dir)
    await writeTree(dir, {
      'src/orders/order.ts': '@Injectable()\nexport class Order {}\n',
    })
    const config = { include: ['src/**/*.ts'], root: 'src' as const }
    await generateModuleGraph({ cwd: dir, config })
    const again = await generateModuleGraph({ cwd: dir, config })
    expect(again.changed).toBe(false)
  })
})
