import { dirname, relative, resolve } from 'node:path'

const HEADER = [
  '// AUTO-GENERATED by @caffeinejs/cli — do not edit or commit',
  '// Regenerate: caffeine generate',
].join('\n')

export interface GenerateModulesOptions {
  files: string[]
  output: string
  importExtension: '.js' | '.ts' | ''
}

export async function generateModules(opts: GenerateModulesOptions): Promise<boolean> {
  const outputDir = dirname(resolve(opts.output))

  const imports = opts.files.map((abs, i) => {
    const rel = relative(outputDir, abs).replaceAll('\\', '/')
    const withSlash = rel.startsWith('.') ? rel : './' + rel
    const withExt = withSlash.replace(/\.ts$/, opts.importExtension)
    return `import * as _${i} from '${withExt}'`
  })

  const picks = opts.files.map((_, i) => `  ..._pick(_${i}),`).join('\n')

  const content = [
    HEADER,
    '',
    'import { kModule } from \'@caffeinejs/core\'',
    'import type { Module } from \'@caffeinejs/core\'',
    ...imports,
    '',
    'function _pick(ns: Record<string, unknown>): Module[] {',
    '  const out: Module[] = []',
    '  if (typeof ns[\'default\'] === \'function\') out.push(ns[\'default\'] as Module)',
    '  for (const [k, v] of Object.entries(ns)) {',
    '    if (k !== \'default\' && typeof v === \'function\' && (v as any)[kModule]) {',
    '      out.push(v as Module)',
    '    }',
    '  }',
    '  return out',
    '}',
    '',
    'export const modules: Module[] = [',
    picks,
    ']',
    '',
  ].join('\n')

  const outputFile = Bun.file(opts.output)
  let existing: string | undefined
  if (await outputFile.exists()) {
    existing = await outputFile.text()
  }

  if (existing !== undefined && hash(existing) === hash(content)) {
    return false
  }

  await Bun.write(opts.output, content)

  return true
}

function hash(content: string): string {
  return new Bun.CryptoHasher('sha1').update(content)
    .digest('hex')
}
