codecov:
  require_ci_to_pass: false

ignore:
  - 'api/**'
  - '**/_tests/**'
  - '**/_testdata/**'
  - '**/*.testkit.ts'
  - 'benchmarks/**'
  - 'docs/**'
  - 'examples/**'
  - 'plugins/**'
  - 'test/**'
  - 'tools/**'

coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true
