sonar.organization=caffeinejs
sonar.projectKey=caffeinejs_caffeine

sonar.exclusions=**/node_modules/**,**/dist/**,benchmarks/**,examples/**,di/examples/**,docs/**,test/**,tools/**,ai/**,coverage/**,plugins/**,**/*.test.ts,**/_testdata/**
sonar.test.exclusions=**/node_modules/**,**/dist/**,benchmarks/**,examples/**,di/examples/**,docs/**,test/**,tools/**,ai/**,coverage/**,plugins/**,**/*.test.ts,**/_testdata/**
