// AUTO-GENERATED by @caffeinejs/cli — do not edit
// Regenerate: caffeine generate modules

import { mod, type Module } from '@caffeinejs/di'
import { utilModule } from '../util/util.gen.mod.js'
import { HomeController } from './home.controller.js'

export const homeModule: Module = mod({
  name: 'home',
  needs: () => [
    utilModule,
  ],
  provides: () => [
    HomeController,
  ],
})
