// AUTO-GENERATED by @caffeinejs/cli — do not edit
// Regenerate: caffeine generate modules

import { mod, type Module } from '@caffeinejs/di'
import { utilModule } from '../util/util.gen.mod.js'
import { GithubAuthController } from './github.controller.js'

export const authModule: Module = mod({
  name: 'auth',
  needs: () => [
    utilModule,
  ],
  provides: () => [
    GithubAuthController,
  ],
})
