import { Type } from '@sinclair/typebox'

export const moduleGraphConfigSchema = Type.Object(
  {
    include: Type.Array(Type.String(), {
      description: 'Globs, relative to the project directory, naming the sources to read',
    }),
    exclude: Type.Optional(
      Type.Array(Type.String(), {
        description: 'Globs removed from the include set, such as bootstrap files and tests',
      }),
    ),
    root: Type.Optional(
      Type.String({
        description: 'Directory the module graph is rooted at, where the root module is written',
        default: 'src',
      }),
    ),
    importExtension: Type.Optional(
      Type.Union([Type.Literal('.js'), Type.Literal('.ts'), Type.Literal('')], {
        description: 'Extension the generated import specifiers carry',
        default: '.js',
      }),
    ),
    depth: Type.Optional(
      Type.Integer({
        minimum: 0,
        description: 'Folder depth, below the root, at which a module is formed',
        default: 1,
      }),
    ),
    depths: Type.Optional(
      Type.Record(Type.String(), Type.Integer({ minimum: 0 }), {
        description: 'Per-folder overrides of depth, keyed by the folder path below the root',
      }),
    ),
    maxDepth: Type.Optional(
      Type.Integer({
        minimum: 0,
        description: 'Folder depth beyond which sources are left out of the graph',
        default: 8,
      }),
    ),
    skip: Type.Optional(
      Type.Array(Type.String(), {
        description: 'Folder paths, below the root, that form no module',
      }),
    ),
  },
  { additionalProperties: false, description: 'Module graph generated by "caffeine generate modules"' },
)

export const caffeineConfigSchema = Type.Object(
  {
    // Declared so a JSON or YAML config can point an editor at this schema without tripping
    // additionalProperties.
    $schema: Type.Optional(Type.String({ description: 'URL or path of this schema' })),
    modules: Type.Optional(moduleGraphConfigSchema),
  },
  { additionalProperties: false },
)
