import { createHash } from 'node:crypto'
import { readFile, writeFile } from 'node:fs/promises'
import { dirname, relative, resolve } from 'node:path'

const HEADER = [
  '// AUTO-GENERATED by @caffeinejs/cli — do not edit or commit',
  '// Regenerate: caffeine generate',
].join('\n')

export interface GenerateOptions {
  files: string[]
  output: string
  importExtension: '.js' | '.ts' | ''
}

export async function generate(opts: GenerateOptions): Promise<boolean> {
  const outputDir = dirname(resolve(opts.output))

  const imports = opts.files
    .map(abs => {
      const rel = relative(outputDir, abs).replaceAll('\\', '/')
      const withSlash = rel.startsWith('.') ? rel : './' + rel
      const withExt = withSlash.replace(/\.ts$/, opts.importExtension)
      return `import '${withExt}'`
    })
    .sort()
    .join('\n')

  const content = `${HEADER}\n\n${imports}\n`

  let existing: string | undefined
  try {
    existing = await readFile(opts.output, 'utf8')
  } catch {
    // file doesn't exist yet
  }

  const newHash = hash(content)
  if (existing !== undefined && hash(existing) === newHash) {
    return false
  }

  await writeFile(opts.output, content, 'utf8')
  return true
}

function hash(content: string): string {
  return createHash('sha1').update(content)
    .digest('hex')
}
