import { dirname, relative, resolve } from 'node:path'

const HEADER = [
  '// AUTO-GENERATED by @caffeinejs/cli — do not edit or commit',
  '// Regenerate: caffeine generate',
].join('\n')

export interface GenerateOptions {
  files: string[]
  output: string
  importExtension: '.js' | '.ts' | ''
}

export async function generate(opts: GenerateOptions): Promise<boolean> {
  const outputDir = dirname(resolve(opts.output))

  const imports = opts.files
    .map(abs => {
      const rel = relative(outputDir, abs).replaceAll('\\', '/')
      const withSlash = rel.startsWith('.') ? rel : './' + rel
      const withExt = withSlash.replace(/\.ts$/, opts.importExtension)
      return `import '${withExt}'`
    })
    .sort()
    .join('\n')

  const content = `${HEADER}\n\n${imports}\n`

  const outputFile = Bun.file(opts.output)
  let existing: string | undefined
  if (await outputFile.exists()) {
    existing = await outputFile.text()
  }

  if (existing !== undefined && hash(existing) === hash(content)) {
    return false
  }

  await Bun.write(opts.output, content)

  return true
}

function hash(content: string): string {
  return new Bun.CryptoHasher('sha1').update(content)
    .digest('hex')
}
