// AUTO-GENERATED by @caffeinejs/cli — do not edit
// Regenerate: caffeine generate modules

import { mod, type Module } from '@caffeinejs/di'
import { authModule } from './auth/auth.gen.mod.js'
import { healthModule } from './health/health.gen.mod.js'
import { homeModule } from './home/home.gen.mod.js'
import { ordersModule } from './orders/orders.gen.mod.js'
import { petsModule } from './pets/pets.gen.mod.js'
import { usersModule } from './users/users.gen.mod.js'
import { utilModule } from './util/util.gen.mod.js'

export const rootModule: Module = mod({
  name: 'root',
  provides: () => [
    authModule,
    healthModule,
    homeModule,
    ordersModule,
    petsModule,
    usersModule,
    utilModule,
  ],
})
