// AUTO-GENERATED by @caffeinejs/cli — do not edit
// Regenerate: caffeine generate modules

import { mod, type Module } from '@caffeinejs/di'
import { authModule } from '../auth/auth.gen.mod.js'
import { AdminController } from './admin.controller.js'

export const adminModule: Module = mod({
  name: 'admin',
  needs: () => [
    authModule,
  ],
  provides: () => [
    AdminController,
  ],
})
