// AUTO-GENERATED by @caffeinejs/cli — do not edit
// Regenerate: caffeine generate modules

import { mod, type Module } from '@caffeinejs/di'
import { utilModule } from '../util/util.gen.mod.js'
import { OrdersRepository } from './orders.repository.js'

export const ordersModule: Module = mod({
  name: 'orders',
  needs: () => [
    utilModule,
  ],
  provides: () => [
    OrdersRepository,
  ],
})
