// AUTO-GENERATED by @caffeinejs/cli — do not edit
// Regenerate: caffeine generate modules

import { mod, type Module } from '@caffeinejs/di'
import { DatabaseHealth } from './db.health.js'

export const healthModule: Module = mod({
  name: 'health',
  provides: () => [
    DatabaseHealth,
  ],
})
