// AUTO-GENERATED by @caffeinejs/cli — do not edit
// Regenerate: caffeine generate modules

import { mod, type Module } from '@caffeinejs/di'
import { utilModule } from '../util/util.gen.mod.js'
import { UsersController } from './users.controller.js'
import { UsersRepository } from './users.repository.js'

export const usersModule: Module = mod({
  name: 'users',
  needs: () => [
    utilModule,
  ],
  provides: () => [
    UsersController,
    UsersRepository,
  ],
})
