// AUTO-GENERATED by @caffeinejs/cli — do not edit
// Regenerate: caffeine generate modules

import { mod, type Module } from '@caffeinejs/di'
import { Users } from './users.js'

export const authModule: Module = mod({
  name: 'auth',
  provides: () => [
    Users,
  ],
})
