// AUTO-GENERATED by @caffeinejs/cli — do not edit
// Regenerate: caffeine generate modules

import { mod, type Module } from '@caffeinejs/di'
import { adminModule } from './admin/admin.gen.mod.js'
import { authModule } from './auth/auth.gen.mod.js'
import { profileModule } from './profile/profile.gen.mod.js'

export const rootModule: Module = mod({
  name: 'root',
  provides: () => [
    adminModule,
    authModule,
    profileModule,
  ],
})
