// AUTO-GENERATED by @caffeinejs/cli — do not edit
// Regenerate: caffeine generate modules

import { mod, type Module } from '@caffeinejs/di'
import { PrismaConfig } from './db/prisma.config.js'
import { FallbackErrorHandler, HTTPErrorHandler } from './errors/error.handlers.js'

export const utilModule: Module = mod({
  name: 'util',
  provides: () => [
    PrismaConfig,
    FallbackErrorHandler,
    HTTPErrorHandler,
  ],
})
