// AUTO-GENERATED by @caffeinejs/cli — do not edit
// Regenerate: caffeine generate modules

import { mod, type Module } from '@caffeinejs/di'
import { ProfileController } from './profile.controller.js'

export const profileModule: Module = mod({
  name: 'profile',
  provides: () => [
    ProfileController,
  ],
})
